version: "3.8"

services:
  printer:
    build: .
    restart: unless-stopped
    environment:
      - LABEL_SIZE=29x90
      - #LABEL_SIZE=62red
      - PRINTER_MODEL=QL-800
      - PRINTER_PATH=file:///dev/usb/lp0
      - BARCODE_FORMAT=QRCode
    devices:
      - '/dev/usb/lp0:/dev/usb/lp0'
    ports:
      - "9285:8000"
